API_KEY = ''
ENDPOINT = 'https://app.datarobot.com/api/v2'
DATE_COL = 'DATE'
SERIES_ID = 'STORE_SKU'
TARGET = 'UNITS'
KA_COLS = ['PROMO_MAX']
DEPLOYMENT_ID = '63f607e3a469e2c1b9bd99da'
APP_INTRO = """
This app helps to make predictions using the DataRobot deployment.
In order to use it, upload a time series prediction dataset, and follow the guidelines to:
* __Modify KA features__: more than one feature can be modified.
* __Make predictions__: based on the original or modified dataset.
* __Plot results__: show actuals and predictions per series, group or just total aggregation.
* __Download prediction__: individual or all runs together.
"""